# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zplug/init.zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
    echo; zplug install
fi

# Then, source plugins and add commands to $PATH
zplug load

export PATH=$HOME/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export BROWSER=/usr/bin/brave
export FONTCONFIG_PATH=~/.config/fontconfig

# ohmyzsh config
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
  # alias-finder
  docker
  docker-compose
  git
  # git-flow
  # gpg-agent
  # keychain
  npm
  # nvm
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
  )
source $ZSH/oh-my-zsh.sh

alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias perf_mode='echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias save_mode='echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias cpu_watch='watch -n.5 "cat /proc/cpuinfo | grep \"^[c]pu MHz\" && sensors"'
alias l='ls -lAhtr'
# alias paru='paru --skipreview'

DOTDROP=~/dotfiles/dotdrop.sh
export DOTDROP_PROFILE='fell'
export DOTDROP_NOBANNER=
if test -f "$DOTDROP"; then
  alias dot="$DOTDROP"
elif type "pip3" > /dev/null; then
  cd ~/dotfiles && 
  git submodule init && 
  git submodule update --recursive --remote &&
  pip3 install --user -r dotdrop/requirements.txt &&
  dotdrop/bootstrap.sh &&
  chmod u+x dotdrop.sh &&
  ./dotdrop.sh install -f
  source ~/.zshrc
else
  echo "Python3 not installed"
fi

export GPG_TTY=$TTY

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
