config:
  backup: true
  create: true
  link_on_import: link
  dotpath: dotfiles
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    link: link_children
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link_children
  d_config_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link_children
  d_config_picom:
    src: config/picom
    dst: ~/.config/picom
    link: link_children
  d_paru:
    src: config/paru
    dst: ~/.config/paru
    link: link_children
  d_redshift:
    src: config/redshift
    dst: ~/.config/redshift
    link: link_children
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
    link: link
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
    link: link
profiles:
  fell:
    dotfiles:
    - f_gitconfig
    - f_zshrc
    - d_mpv
    - d_kitty
    - d_config_rofi
    - d_config_picom
    - d_paru
    - d_redshift
    - d_fontconfig
    - f_p10k.zsh
