config:
  backup: true
  create: true
  link_on_import: link
  dotpath: dotfiles
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  f_env.zsh:
    src: env.zsh
    dst: ~/.env.zsh
    link: link
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    link: link_children
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link_children
  d_paru:
    src: config/paru
    dst: ~/.config/paru
    link: link_children
  d_redshift:
    src: config/redshift
    dst: ~/.config/redshift
    link: link_children
  f_tmux.conf:
    src: byobu/.tmux.conf
    dst: ~/.byobu/.tmux.conf
    link: link
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
    link: link
  f_ksnip.conf:
    src: config/ksnip/ksnip.conf
    dst: ~/.config/ksnip/ksnip.conf
profiles:
  fell:
    dotfiles:
    - f_gitconfig
    - f_env.zsh
    - d_mpv
    - d_kitty
    - d_paru
    - d_redshift
    - f_tmux.conf
    - f_config
    - f_ksnip.conf
